[build]
  publish = "public"
  command = "yarn build"
  functions = "lambda"

[build.environment]
  YARN_VERSION = "1.21.1"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 301
  
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
